---
# https://docs.github.com/en/actions/quickstart
# hhttps://github.com/marketplace/actions/build-and-publish-docker-image-to-github-container-registry
name: "Terraform Modules Library Pipeline"

on: # yamllint disable-line rule:truthy
  push: # yamllint disable-line rule:empty-values

env:
  TF_CLOUD_ORGANIZATION: "nolan"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-modules-library"
  CONFIG_DIRECTORY: "./"

jobs:
  build-and-publish-latest:
    if: ${{ vars.REBUILD_CONTAINER_IMAGE == 'true' }}
    runs-on: ubuntu-latest

    steps:
      # Checking out the repo
      - uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      # https://blog.thesparktree.com/docker-multi-arch-github-actions
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,amd64'

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # https://github.com/docker/metadata-action#tags-input
          # tags: ${{ steps.meta.outputs.tags }}
          tags: ghcr.io/${{ github.repository_owner }}/terraform-modules-library-container:latest # INFO: Hardcoding latest tag
          labels: ${{ steps.meta.outputs.labels }}

  run-run-dot-sh:
    runs-on: ubuntu-latest
    needs: build-and-publish-latest
    if: |
      always() &&
      (needs.build-and-publish-latest.result == 'success' || needs.build-and-publish-latest.result == 'skipped')
    container:
      image: ghcr.io/${{ github.repository_owner }}/terraform-modules-library-container:latest # INFO: Pinned to latest tag
      options: --user 1001

    steps:
      # Checking out the repo
      - uses: actions/checkout@v3

      - name: Terraform version
        run: terraform -v

      - name: Copy /home/ubuntu/.tflint.d to /github/home/
        run: cp -r /home/ubuntu/.tflint.d /github/home/

      - name: Install Pre Commit
        run: python3 -m pip install --no-cache-dir --quiet --upgrade --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org git+https://github.com/pre-commit/pre-commit.git@v2.20.0

      - name: cd GITHUB_WORKSPACE
        run: cd $GITHUB_WORKSPACE

      - name: Run
        run: ./run.sh

  push-modules-and-patterns-upstream:
    runs-on: ubuntu-latest
    needs: run-run-dot-sh
    if: |
      always() &&
      (needs.run-run-dot-sh.result == 'success' || needs.run-run-dot-sh.result == 'skipped')
    container:
      image: ghcr.io/${{ github.repository_owner }}/terraform-modules-library-container:latest # INFO: Pinned to latest tag
      options: --user 1001

    steps:
      # Checking out the repo
      - uses: actions/checkout@v3

      - name: cd GITHUB_WORKSPACE
        run: cd $GITHUB_WORKSPACE

      # - name: Debug
      #   run: git config --list; pwd; ls -la; ls -la aws/modules/debug/; tree -L 4

      # - name: Env
      #   run: env

      - name: Push Modules and Patterns Upstream
        run: make push-modules-and-patterns-upstream
        env:
          ACCESS_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN_GITHUB }}

  terraform-plan-on-tfc:
    needs: push-modules-and-patterns-upstream
    if: |
      always() &&
      (needs.push-modules-and-patterns-upstream.result == 'success' || needs.push-modules-and-patterns-upstream.result == 'skipped')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/terraform-modules-library-container:latest
      options: --user 1001

    steps:
      - uses: actions/checkout@v3

      - name: Upload Configuration aws/modules/terraform-aws-debug
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: aws-modules-terraform-aws-debug-plan-upload
        with:
          workspace: "terraform-modules-library"
          directory: "./aws/modules/terraform-aws-debug"
          speculative: true

      - name: Create Plan Run aws/modules/debug
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: aws-modules-terraform-aws-debug-plan-run
        with:
          workspace: "terraform-modules-library"
          configuration_version: ${{ steps.aws-modules-terraform-aws-debug-plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Upload Configuration custom/modules/terraform-custom-debug
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
        id: custom-modules-terraform-custom-debug-plan-upload
        with:
          workspace: "terraform-modules-library"
          directory: "./custom/modules/terraform-custom-debug"
          speculative: true

      - name: Create Plan Run custom/modules/debug
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.4
        id: custom-modules-terraform-custom-debug-plan-run
        with:
          workspace: "terraform-modules-library"
          configuration_version: ${{ steps.custom-modules-terraform-custom-debug-plan-upload.outputs.configuration_version_id }}
          plan_only: true
