# https://docs.github.com/en/actions/quickstart
# hhttps://github.com/marketplace/actions/build-and-publish-docker-image-to-github-container-registry
name: "Terraform Modules Library Pipeline"

on:
  push:

# env:
#   TF_CLOUD_ORGANIZATION: "nolan"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "terraform-hashicorp-hashiqube"
#   CONFIG_DIRECTORY: "./"

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    # Running this job only for master branch
    # if: github.ref == 'refs/heads/main'

    steps:
      # Checking out the repo
      - uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      # https://blog.thesparktree.com/docker-multi-arch-github-actions
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,amd64'

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/marketplace/actions/docker-build-push-action
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and Push Docker image
        with:
          image: terraform-modules-library-container
          tags: latest
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
